plugins {
    id 'com.android.application'
}

android {
    compileSdkVersion 33
    defaultConfig {
        applicationId "com.example.vulnerablebank"
        minSdkVersion 21
        targetSdkVersion 33
        versionCode 1
        versionName "1.0.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false       // Pas d'obfuscation en production
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            // debuggable laissé à true par erreur
            debuggable true
        }
        debug {
            debuggable true
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    // Bibliothèques non mises à jour avec des CVE connues
    implementation 'com.squareup.okhttp3:okhttp:3.12.0'   // CVE-2021-0341
    implementation 'org.apache.commons:commons-compress:1.19' // CVE-2021-35515
    testImplementation 'junit:junit:4.13.2'
}
